# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='\u0627\u062e\u062a\u0635\u0627\u0631 \u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='\u0631\u0645\u0632 \u0627\u0644\u0645\u0627\u062f\u0629'),
        ),
    ]
