# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170407_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629'),
        ),
    ]
