# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0627\u0627\u0644\u0627\u0633\u0645')),
                ('photo', models.ImageField(upload_to=b'', verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629')),
                ('slug', models.SlugField(max_length=40, verbose_name='\u0627\u0644\u0631\u0627\u0628\u0637')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0625\u0646\u062c\u0644\u064a\u0632\u064a')),
                ('upload_date', models.DateField(max_length=100, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0625\u0636\u0627\u0641\u0629')),
                ('upload', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u0645\u0644\u0641')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Category', verbose_name='\u0627\u0644\u062a\u0635\u0646\u064a\u0641')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0640/\u0640\u0629')),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0631\u0641\u0639')),
                ('status', models.CharField(choices=[('SUB', '\u0623\u0631\u0633\u0644'), ('PUB', '\u0645\u0646\u0634\u0648\u0631'), ('REJ', '\u0645\u0631\u0641\u0648\u0636')], default='AVL', max_length=3, verbose_name='\u0627\u0644\u062d\u0627\u0644\u0629')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File', verbose_name='\u0627\u0644\u0645\u0644\u0641')),
            ],
        ),
    ]
