# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='quizlet_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='\u0643\u0648\u064a\u0632\u0644\u062a'),
        ),
        migrations.AddField(
            model_name='file',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='\u064a\u0648\u062a\u064a\u0648\u0628'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0627\u0644\u0645\u0644\u0641'),
        ),
    ]
