# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170407_0150'),
        ('files', '0004_auto_20170407_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0625\u0646\u062c\u0644\u064a\u0632\u064a')),
                ('document', models.FileField(upload_to='documents/', verbose_name='\u0627\u0644\u0645\u0644\u0641')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0625\u0636\u0627\u0641\u0629')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='\u0627\u0644\u062a\u0635\u0646\u064a\u0641')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='quizlet',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='contributor',
        ),
        migrations.AddField(
            model_name='quizlet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='\u0627\u0644\u062a\u0635\u0646\u064a\u0641'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='\u0627\u0644\u062a\u0635\u0646\u064a\u0641'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Document', verbose_name='\u0627\u0644\u0645\u0644\u0641'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
